# Safety policy file for packages needed for development.
# For documentation, see https://docs.safetycli.com/safety-docs/administration/safety-policy-files

# Note: This policy file is used against the versions in minimum-constraints-develop.txt.

version: '3.0'

scanning-settings:
  max-depth: 6
  exclude: []
  include-files: []
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      vulnerabilities:
          # List of specific vulnerabilities to ignore.
          # {id}:                 # vulnerability ID
          #     reason: {text}    # optional: Reason for ignoring it
          #     expires: {date}   # optional: Date when this ignore will expire
          70612:
              reason: Disputed issue in jinja2 version 3.1.3 - No known fix

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - high
        - medium
        - critical
      exploitability:
        - high
        - medium
        - critical

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

installation:
  default-action: allow
  audit-logging:
    enabled: true
  allow:
    packages: []
    vulnerabilities: {}
  deny:
    packages: {}
    vulnerabilities:
      warning-on-any-of:
        cvss-severity: []
      block-on-any-of:
        cvss-severity: []
